### ISSUE TITLE
OSError: Error relocating /venv/lib/python3.11/site-packages/rticonnextdds-connector/lib/linux-x64/libnddscore.so: backtrace: symbol not found

### ISSUE THREAD

**Issue by Hongbo-Miao** [rticommunity/rticonnextdds-connector-py#158]
I have an `Flask` server which is using `rticonnextdds-connector-py`.
I successfully built the docker image. Now I am trying to run it, however, I got this error:

```sh
$ docker run --publish=5516:5516 --name=my-service --rm my-service:test
[2022-12-06 23:31:34 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2022-12-06 23:31:34 +0000] [7] [INFO] Listening at: http://0.0.0.0:5516 (7)
[2022-12-06 23:31:34 +0000] [7] [INFO] Using worker: sync
[2022-12-06 23:31:34 +0000] [8] [INFO] Booting worker with pid: 8
[2022-12-06 23:31:34 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/venv/lib/python3.11/site-packages/my_service/__init__.py", line 10, in <module>
    from my_rti_controller import RecorderState, ServiceState
  File "/venv/lib/python3.11/site-packages/my_rti_controller/__init__.py", line 2, in <module>
    from .my_rti_controller import (
  File "/venv/lib/python3.11/site-packages/my_rti_controller/my_rti_controller.py", line 16, in <module>
    import rticonnextdds_connector as rti
  File "/venv/lib/python3.11/site-packages/rticonnextdds_connector/__init__.py", line 9, in <module>
    from .rticonnextdds_connector import *
  File "/venv/lib/python3.11/site-packages/rticonnextdds_connector/rticonnextdds_connector.py", line 372, in <module>
    connector_binding = _ConnectorBinding() # pylint: disable=invalid-name
                        ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/rticonnextdds_connector/rticonnextdds_connector.py", line 170, in __init__
    self.library = ctypes.CDLL(os.path.join(path, libname), ctypes.RTLD_GLOBAL)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: Error relocating /venv/lib/python3.11/site-packages/rticonnextdds-connector/lib/linux-x64/libnddscore.so: backtrace: symbol not found
[2022-12-06 23:31:34 +0000] [8] [INFO] Worker exiting (pid: 8)
[2022-12-06 23:31:34 +0000] [7] [INFO] Shutting down: Master
[2022-12-06 23:31:34 +0000] [7] [INFO] Reason: Worker failed to boot.
```

If I sh into the Docker container, it does have this file `/venv/lib/python3.11/site-packages/rticonnextdds-connector/lib/linux-x64/libnddscore.so`:

```sh
$ docker run --rm -it --entrypoint sh my-service:test
> cd /venv/lib/python3.11/site-packages/rticonnextdds-connector/lib/linux-x64
> ls
libnddsc.so            libnddscore.so         librtiddsconnector.so
```

Any idea regarding this error? Could it be related with some "property" with `libnddscore.so` that cannot be read by `rticonnextdds-connector-py` correctly?
Any insights would be appreciate. Thanks! 😃

**Comment by Hongbo-Miao** [comment]
Found the issue, when run `ldd libnddscore.so`, it will reveal the error:

```sh
> ldd libnddscore.so
	/lib/ld-musl-x86_64.so.1 (0x7f95cd94a000)
	librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f95cd94a000)
	libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7f95cd94a000)
	libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f95cd94a000)
	libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7f95cd94a000)
	libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f95cd94a000)
Error relocating libnddscore.so: backtrace: symbol not found
Error relocating libnddscore.so: __rawmemchr: symbol not found
Error relocating libnddscore.so: backtrace_symbols: symbol not found
Error relocating libnddscore.so: __isnan: symbol not found
Error relocating libnddscore.so: __isinf: symbol not found
```

## Method 1 (Failed, but can potentially succeed)

Adding GNU C library glibc inside Python alpine-based image: [https://github.com/sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc)
For this one, after installing, `libnddscore.so` still points to musl C libraries. I did set these two in Docker ENV, but still no luck

```Dockerfile
ENV LD_LIBRARY_PATH=/usr/glibc-compat/lib:${LD_LIBRARY_PATH}
ENV PATH=/usr/glibc-compat/sbin:/usr/glibc-compat/bin:${PATH}
```

I can confirm all lib files I want are inside the docker container though:

```sh
> cd /usr/glibc-compat/lib

> ls
ld-linux-x86-64.so.2    libc.so                 libdl.so.2              libnsl.so.1             libnss_files.so.2       libresolv.so.2
libBrokenLocale.so      libc.so.6               libm.so                 libnss_compat.so        libnss_hesiod.so        librt.so.1
libBrokenLocale.so.1    libc_malloc_debug.so    libm.so.6               libnss_compat.so.2      libnss_hesiod.so.2      libthread_db.so
libSegFault.so          libc_malloc_debug.so.0  libmemusage.so          libnss_db.so            libpcprofile.so         libthread_db.so.1
libanl.so               libcrypt.so             libmvec.so              libnss_db.so.2          libpthread.so.0         libutil.so.1
libanl.so.1             libcrypt.so.1           libmvec.so.1            libnss_dns.so.2         libresolv.so            locale
```

## Method 2 (Failed, but can potentially succeed)

Pre-built alpine image with GNU C library glibc: [https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc](https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc)
This one is missing pip and Python 3.11 I am using, and the default `apk update && apk add --no-cache py-pip` will give Python 3.10.
Setting up these is very tedious work though, not good for long term maintenance.

## Method 3 (Succeed)

Python actually start to have a new `bullseye` serial images recently which are using GNU C that I am not aware of.Both `python:3.11.0-bullseye` and `python:3.11.0-slim-bullseye` images work, however `python:3.11.0-slim-bullseye` is much smaller size (~40MB vs ~300MB).
